#Docker image pipline
image: samueldebruyn/debian-git
pipelines:
  default:
    - step:
       name: Check Updates
       script: # steps
         
    - step:
       name: Deploy in to Beta Environment and Functional Test
       script:
         - apt-get -qq install git-ftp
         - yes | git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in/public_html/beta.pilti.in