#Docker image pipline

image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
       script: # steps
         - apt-get update
         - apt-get -qq install git-ftp
         - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in:21/public_html/beta.pilti.in/