#Docker image pipline
image: samueldebruyn/debian-git
pipelines:
  default:
    - step:
       name: Update
       script: # steps
         - apt-get update
         
    - step:
       name: Test
       script:
       - cat "Test"
      
    - step:
       name: Insatll GIT FTP
       script: # steps
         - apt-get -qq install git-ftp
         
    - step:
       name: Deploy Website
       script: # steps
         - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in/public_html/beta.pilti.in