#Docker image pipline

image: samueldebruyn/debian-git

pipelines:
  default:
    name: Update
    - step:
       script: # steps
         - apt-get update
    name: Test 
    - step:
    name: Insatll GIT FTP
    - step:
       script: # steps
         - apt-get -qq install git-ftp
    name: Deploy website
    - step:
       script: # steps
         - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in/public_html/beta.pilti.in