#Docker image pipline
image: samueldebruyn/debian-git
pipelines:
  default:
    - step:
       name: Check Updates
       script: # steps
         - apt-get update
         
    - step:
       name: Deploy in to Beta Environment and Functional Test
       script:
       - apt-get update
         - apt-get -qq install git-ftp
         - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in/public_html/beta.pilti.in
      
    - step:
       name: Deploy in to Pre-Prod Environment and Performance Test
       script: # steps
         - apt-get update
         - apt-get -qq install git-ftp
         - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in/public_html/beta.pilti.in
         
    - step:
       name: Deploy Website for Public
       script: # steps
         - apt-get update
         - apt-get -qq install git-ftp
         - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://pilti.in/public_html/beta.pilti.in