#Docker image pipline

image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
       script: # steps
         - apt-get update
         - apt-get -qq install git-ftp
         - git ftp init --user Umesh@pilti.in --passwd Mother-123 ftp://pilti.in/public_html/beta.pilti.in